### PR TITLE
Drafts environment variables on application

### PR DESCRIPTION
**Pull request by itays123**
I also added the mailing service to this pr

### CODE REVIEW

**Review by davidmeirlevy — APPROVED** [review]
It's great. I will merge it after I'll handle the npm packages of those service.

**Comment by itays123** [comment]
Thanks

**Comment by davidmeirlevy** [comment]
please remove the "mailing" service from this PR, because the mailing service is still not ready, and we cannot wait for it to merge.

**Comment by itays123** [comment]
Done!

**Review by davidmeirlevy — APPROVED** [review]

**Pull request merged**
